export const BEGIN_AJAX_CALL = 'bac';
export const AJAX_CALL_ERROR = 'ace';

export const LOAD_COURSES_SUCCESS = 'LOAD COURSES SUCCESS';
export const CREATE_COURSE_SUCCESS = 'ccSUCCESS';
export const UPDATE_COURSE_SUCCESS = 'ucSUCCESS';
export const DELETE_COURSE_SUCCESS = 'dcSUCCESS';

export const LOAD_AUTHORS_SUCCESS = 'LOAD AUTHORS SUCCESS';
export const CREATE_AUTHOR_SUCCESS = 'caSUCCESS';
export const UPDATE_AUTHOR_SUCCESS = 'uaSUCCESS';
export const DELETE_AUTHOR_SUCCESS = 'daSUCCESS';
